### ISSUE TITLE
☔ converting problem 

### ISSUE THREAD

**Issue by emin** [iamcal/js-emoji#68]
When converting ☔, EmojiConvertor converts it to `:umbrella_with_rain_drops:` however it should be `:umbrella:`

**Comment by iamcal** [comment]
this is intentional. unfortunately when emoji were first introduced, short-names were used which didn't match the official Unicode names. This was fine until Unicode 8 where additional emoji were introduced that had official names matching the short-names already in-use. Since js-emoji (and emoji-data that powers it) can represent far more emoji than e.g. GitHub, this is one of a few backward-incompatible changes.
